services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network
    restart: always

  java-app:
    image: openjdk:17
    container_name: java-app-container
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["java", "-jar", "demo1.jar"]
    networks:
      - app-network
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge